if (NOT TBB_FOUND)
  if (TBB_FIND_REQUIRED)
    set(_TBB_FIND_REQUIRED ${TBB_FIND_REQUIRED})
    unset(TBB_FIND_REQUIRED)
  else()
    unset(_TBB_FIND_REQUIRED)
  endif()
  find_package(TBB CONFIG QUIET)
  if (_TBB_FIND_REQUIRED)
    set(TBB_FIND_REQUIRED ${_TBB_FIND_REQUIRED})
    unset(_TBB_FIND_REQUIRED)
  endif()
  if (TBB_FOUND)
    set(_TBB_config_mode CONFIG_MODE)
  else()
    unset(_TBB_config_mode)
  endif()
endif()

if (NOT TARGET TBB::tbb)
  if (NOT TBB_FOUND)
    find_library(_TBB_lib tbb HINTS ${TBB_LIB})
    if (_TBB_lib)
      set(TBB_FOUND TRUE)
      set(TBB ${_TBB_lib})
    endif()
  endif()
  add_library(TBB::tbb SHARED IMPORTED)
  set_target_properties(TBB::tbb PROPERTIES IMPORTED_LOCATION ${TBB})
endif()

set(TBB_FIND_REQUIRED ${_TBB_FIND_REQUIRED})
include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(TBB ${_tbb_config_mode} REQUIRED_VARS TBB_FOUND)

unset(_TBB_FIND_REQUIRED)
unset(_TBB_lib CACHE)
unset(_TBB_config_mode)
